name: "Terraform Approval Action"
description: "Runs Terraform plan and creates approval issue"

inputs:
  region:
    required: true
  environment:
    required: true
  working_directory:
    required: true

runs:
  using: "composite"
  steps:

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS Credentials
      shell: bash
      run: |
        echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $GITHUB_ENV
        echo "AWS_DEFAULT_REGION=${{ inputs.region }}" >> $GITHUB_ENV

    - name: Terraform Init
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: terraform init -backend-config=backend.config

    - name: Terraform Validate
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: terraform validate

    - name: Terraform Plan
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: terraform plan -no-color > plan.txt

    - name: Create Approval Issue
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        WORKFLOW_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"

        BODY_FILE="issue_body.txt"

        echo "Terraform plan generated for environment: ${{ inputs.environment }}" > $BODY_FILE
        echo "" >> $BODY_FILE
        echo "Region: ${{ inputs.region }}" >> $BODY_FILE
        echo "" >> $BODY_FILE
        echo "Workflow Run:" >> $BODY_FILE
        echo "$WORKFLOW_URL" >> $BODY_FILE
        echo "" >> $BODY_FILE
        echo "Review plan and approve before apply." >> $BODY_FILE

        jq -n \
          --arg title "Terraform Approval Required - ${{ inputs.environment }}" \
          --arg body "$(cat $BODY_FILE)" \
          '{title: $title, body: $body, labels: ["terraform","approval"]}' \
          > issue.json

        RESPONSE=$(curl -X POST \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/$GITHUB_REPOSITORY/issues \
          -d @issue.json)
        ISSUE_URL=$(echo "$RESPONSE" | jq -r '.html_url')

        echo "Issue URL: $ISSUE_URL"

        echo "issue_url=$ISSUE_URL" >> $GITHUB_OUTPUT
    - name: Print Issue URL
      shell: bash
      run: |
        echo "Approval Issue Created:"
        echo "${{ steps.create_issue.outputs.issue_url }}"
